# config.example.py

WAZUH_MANAGER_IP = "YOUR_WAZUH_MANAGER_IP"
UBUNTU_TARGET_IP = "YOUR_UBUNTU_TARGET_IP"
WINDOWS_ANALYST_IP = "YOUR_WINDOWS_ANALYST_IP"

WAZUH_URL = f"https://{WAZUH_MANAGER_IP}:55000"
INDEXER_URL = f"https://{WAZUH_MANAGER_IP}:9200"

PROTECTED_IPS = {
    WINDOWS_ANALYST_IP,
    WAZUH_MANAGER_IP,
    UBUNTU_TARGET_IP,
    "KALI_ATTACKER_IP",
    "127.0.0.1"
}
